name: Update Json

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install modules
      run: pip install -r requirements.txt
    - name: Get Recipes
      env:
        MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
        MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      run: python request.py
    - name: Commit and Push
      run: |
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git config --global user.name ${{ secrets.USER_NAME }}
        git add recipes.json
        git commit -m "feat: auto commitment:${{ env.CURRENT_DATETIME }}"
        git push origin main
